# Generated by Django 4.2.2 on 2023-08-18 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credentials', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='material',
            field=models.TextField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='purpose',
            field=models.TextField(max_length=50, null=True),
        ),
    ]
